// Package table provides a simple table component for Bubble Tea applications.
package table

import (
	"strings"

	"charm.land/bubbles/v2/help"
	"charm.land/bubbles/v2/key"
	"charm.land/bubbles/v2/viewport"
	tea "charm.land/bubbletea/v2"
	"charm.land/lipgloss/v2"
	"github.com/charmbracelet/x/ansi"
)

// Model defines a state for the table widget.
type Model struct {
	KeyMap KeyMap
	Help   help.Model

	cols      []Column
	rows      []Row
	mode      Mode
	cursor    [2]int // [row, col]
	focus     bool
	styles    Styles
	styleFunc StyleFunc

	viewport viewport.Model
	start    int
	end      int
}

// Mode represents different states the table could be in. This can affect
// rendering and other behavior.
type Mode int

const (
	// ModeNormal is the default row selection mode.
	ModeNormal Mode = iota
	// ModeCell is the cell selection mode.
	ModeCell
)

// Row represents one line in the table.
type Row []string

// Column defines the table structure.
type Column struct {
	Title string
	Width int
}

// KeyMap defines keybindings. It satisfies to the help.KeyMap interface, which
// is used to render the help menu.
type KeyMap struct {
	RowUp         key.Binding
	RowDown       key.Binding
	ColumnLeft    key.Binding
	ColumnRight   key.Binding
	PageUp        key.Binding
	PageDown      key.Binding
	HalfPageUp    key.Binding
	HalfPageDown  key.Binding
	GotoTop       key.Binding
	GotoBottom    key.Binding
	SetNormalMode key.Binding
}

// ShortHelp implements the KeyMap interface.
func (km KeyMap) ShortHelp() []key.Binding {
	return []key.Binding{km.RowUp, km.RowDown, km.ColumnLeft, km.ColumnRight, km.SetNormalMode}
}

// FullHelp implements the KeyMap interface.
func (km KeyMap) FullHelp() [][]key.Binding {
	return [][]key.Binding{
		{km.RowUp, km.RowDown, km.ColumnLeft, km.ColumnRight},
		{km.PageUp, km.PageDown, km.HalfPageUp, km.HalfPageDown},
		{km.GotoTop, km.GotoBottom, km.SetNormalMode},
	}
}

// StyleFunc is a function that can be used to customize the style of a table
// cell based on the current render context.
type StyleFunc func(ctx RenderContext) lipgloss.Style

// RenderContext contains the model's current state, useful for cell styling.
type RenderContext struct {
	// Cursor is the current [row, column] position of the table selection.
	Cursor [2]int
	// Cell is the [row, column] position of the cell being rendered.
	Cell [2]int
	// Value is the string content of the cell.
	Value string
	// Mode indicates the current table mode.
	Mode Mode
	// IsFocused indicates whether the table is currently focused.
	IsFocused bool
}

// DefaultKeyMap returns a default set of keybindings.
func DefaultKeyMap() KeyMap {
	return KeyMap{
		RowUp: key.NewBinding(
			key.WithKeys("up", "k"),
			key.WithHelp("↑/k", "up"),
		),
		RowDown: key.NewBinding(
			key.WithKeys("down", "j"),
			key.WithHelp("↓/j", "down"),
		),
		ColumnLeft: key.NewBinding(
			key.WithKeys("h", "left"),
			key.WithHelp("h/←", "left"),
		),
		ColumnRight: key.NewBinding(
			key.WithKeys("l", "right"),
			key.WithHelp("l/→", "right"),
		),
		PageUp: key.NewBinding(
			key.WithKeys("b", "pgup"),
			key.WithHelp("b/pgup", "page up"),
		),
		PageDown: key.NewBinding(
			key.WithKeys("f", "pgdown", "space"),
			key.WithHelp("f/pgdn", "page down"),
		),
		HalfPageUp: key.NewBinding(
			key.WithKeys("u", "ctrl+u"),
			key.WithHelp("u", "½ page up"),
		),
		HalfPageDown: key.NewBinding(
			key.WithKeys("d", "ctrl+d"),
			key.WithHelp("d", "½ page down"),
		),
		GotoTop: key.NewBinding(
			key.WithKeys("home", "g"),
			key.WithHelp("g/home", "go to start"),
		),
		GotoBottom: key.NewBinding(
			key.WithKeys("end", "G"),
			key.WithHelp("G/end", "go to end"),
		),
		SetNormalMode: key.NewBinding(
			key.WithKeys("esc"),
			key.WithHelp("esc", "return to normal mode"),
		),
	}
}

// Styles contains style definitions for this list component. By default, these
// values are generated by DefaultStyles.
type Styles struct {
	Header   lipgloss.Style
	Cell     lipgloss.Style
	Selected lipgloss.Style
}

// DefaultStyles returns a set of default style definitions for this table.
func DefaultStyles() Styles {
	return Styles{
		Selected: lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("212")),
		Header:   lipgloss.NewStyle().Bold(true).Padding(0, 1),
		Cell:     lipgloss.NewStyle().Padding(0, 1),
	}
}

// SetStyles sets the table styles.
func (m *Model) SetStyles(s Styles) {
	m.styles = s
	m.UpdateViewport()
}

// Option is used to set options in New. For example:
//
//	table := New(WithColumns([]Column{{Title: "ID", Width: 10}}))
type Option func(*Model)

// New creates a new model for the table widget.
func New(opts ...Option) Model {
	m := Model{
		viewport: viewport.New(viewport.WithHeight(20)), //nolint:mnd

		KeyMap: DefaultKeyMap(),
		Help:   help.New(),
		styles: DefaultStyles(),
	}

	for _, opt := range opts {
		opt(&m)
	}

	m.UpdateViewport()

	return m
}

// WithColumns sets the table columns (headers).
func WithColumns(cols []Column) Option {
	return func(m *Model) {
		m.cols = cols
	}
}

// WithRows sets the table rows (data).
func WithRows(rows []Row) Option {
	return func(m *Model) {
		m.rows = rows
	}
}

// WithHeight sets the height of the table.
func WithHeight(h int) Option {
	return func(m *Model) {
		m.viewport.SetHeight(h - lipgloss.Height(m.headersView()))
	}
}

// WithWidth sets the width of the table.
func WithWidth(w int) Option {
	return func(m *Model) {
		m.viewport.SetWidth(w)
	}
}

// WithFocused sets the focus state of the table.
func WithFocused(f bool) Option {
	return func(m *Model) {
		m.focus = f
	}
}

// WithStyles sets the table styles.
func WithStyles(s Styles) Option {
	return func(m *Model) {
		m.styles = s
	}
}

// WithStyleFunc sets the table style func which can be determined cell style
// per column, row, and selected state.
func WithStyleFunc(f StyleFunc) Option {
	return func(m *Model) {
		m.styleFunc = f
	}
}

// WithKeyMap sets the key map.
func WithKeyMap(km KeyMap) Option {
	return func(m *Model) {
		m.KeyMap = km
	}
}

// Update is the Bubble Tea update loop.
func (m Model) Update(msg tea.Msg) (Model, tea.Cmd) {
	if !m.focus {
		return m, nil
	}

	switch msg := msg.(type) {
	case tea.KeyPressMsg:
		switch {
		case key.Matches(msg, m.KeyMap.RowUp):
			m.MoveUp(1)
		case key.Matches(msg, m.KeyMap.RowDown):
			m.MoveDown(1)
		case key.Matches(msg, m.KeyMap.ColumnLeft):
			m.MoveLeft(1)
		case key.Matches(msg, m.KeyMap.ColumnRight):
			m.MoveRight(1)
		case key.Matches(msg, m.KeyMap.PageUp):
			m.MoveUp(m.viewport.Height())
		case key.Matches(msg, m.KeyMap.PageDown):
			m.MoveDown(m.viewport.Height())
		case key.Matches(msg, m.KeyMap.HalfPageUp):
			m.MoveUp(m.viewport.Height() / 2) //nolint:mnd
		case key.Matches(msg, m.KeyMap.HalfPageDown):
			m.MoveDown(m.viewport.Height() / 2) //nolint:mnd
		case key.Matches(msg, m.KeyMap.GotoTop):
			m.GotoTop()
		case key.Matches(msg, m.KeyMap.GotoBottom):
			m.GotoBottom()
		case key.Matches(msg, m.KeyMap.SetNormalMode):
			m.SetMode(ModeNormal)
		}
	}

	return m, nil
}

// Focused returns the focus state of the table.
func (m Model) Focused() bool {
	return m.focus
}

// Focus focuses the table, allowing the user to move around the rows and
// interact.
func (m *Model) Focus() {
	m.focus = true
	m.UpdateViewport()
}

// Blur blurs the table, preventing selection or movement.
func (m *Model) Blur() {
	m.focus = false
	m.UpdateViewport()
}

// View renders the component.
func (m Model) View() string {
	return m.headersView() + "\n" + m.viewport.View()
}

// HelpView is a helper method for rendering the help menu from the keymap.
// Note that this view is not rendered by default and you must call it
// manually in your application, where applicable.
func (m Model) HelpView() string {
	return m.Help.View(m.KeyMap)
}

// UpdateViewport updates the list content based on the previously defined
// columns and rows.
func (m *Model) UpdateViewport() {
	renderedRows := make([]string, 0, len(m.rows))

	// Render only rows from: m.cursor-m.viewport.Height to: m.cursor+m.viewport.Height
	// Constant runtime, independent of number of rows in a table.
	// Limits the number of renderedRows to a maximum of 2*m.viewport.Height
	if m.cursor[0] >= 0 {
		m.start = clamp(m.cursor[0]-m.viewport.Height(), 0, m.cursor[0])
	} else {
		m.start = 0
	}
	m.end = clamp(m.cursor[0]+m.viewport.Height(), m.cursor[0], len(m.rows))
	for i := m.start; i < m.end; i++ {
		renderedRows = append(renderedRows, m.renderRow(i))
	}

	m.viewport.SetContent(
		lipgloss.JoinVertical(lipgloss.Left, renderedRows...),
	)
}

// SelectedRow returns the selected row.
// You can cast it to your own implementation.
func (m Model) SelectedRow() Row {
	if m.cursor[0] < 0 || m.cursor[0] >= len(m.rows) {
		return nil
	}

	return m.rows[m.cursor[0]]
}

// SelectedCell returns the selected cell value.
func (m Model) SelectedCell() string {
	if m.cursor[0] < 0 || m.cursor[0] >= len(m.rows) ||
		m.cursor[1] < 0 || m.cursor[1] >= len(m.cols) {
		return ""
	}

	return m.rows[m.cursor[0]][m.cursor[1]]
}

// Rows returns the current rows.
func (m Model) Rows() []Row {
	return m.rows
}

// Columns returns the current columns.
func (m Model) Columns() []Column {
	return m.cols
}

// SetRows sets a new rows state.
func (m *Model) SetRows(r []Row) {
	m.rows = r

	if m.cursor[0] > len(m.rows)-1 {
		m.cursor[0] = len(m.rows) - 1
	}

	m.UpdateViewport()
}

// SetColumns sets a new columns state.
func (m *Model) SetColumns(c []Column) {
	m.cols = c
	m.UpdateViewport()
}

// SetWidth sets the width of the viewport of the table.
func (m *Model) SetWidth(w int) {
	m.viewport.SetWidth(w)
	m.UpdateViewport()
}

// SetHeight sets the height of the viewport of the table.
func (m *Model) SetHeight(h int) {
	m.viewport.SetHeight(h - lipgloss.Height(m.headersView()))
	m.UpdateViewport()
}

// Height returns the viewport height of the table.
func (m Model) Height() int {
	return m.viewport.Height()
}

// Width returns the viewport width of the table.
func (m Model) Width() int {
	return m.viewport.Width()
}

// Cursor returns the indices of the selected row and column [row, col].
func (m Model) Cursor() [2]int {
	return m.cursor
}

// SetCursor sets the cursor position in the table. If a value is negative, that
// position won't be updated.
func (m *Model) SetCursor(row, col int) {
	prev := m.cursor
	if row >= 0 {
		m.cursor[0] = clamp(row, 0, len(m.rows)-1)
	}
	if col >= 0 {
		m.cursor[1] = clamp(col, 0, len(m.cols)-1)
	}
	if prev != m.cursor {
		m.UpdateViewport()
	}
}

// MoveUp moves the selection up by n number of rows.
// It can not go above the first row.
func (m *Model) MoveUp(n int) {
	m.cursor[0] = clamp(m.cursor[0]-n, 0, len(m.rows)-1)

	offset := m.viewport.YOffset()
	switch {
	case m.start == 0:
		offset = clamp(offset, 0, m.cursor[0])
	case m.start < m.viewport.Height():
		offset = clamp(clamp(offset+n, 0, m.cursor[0]), 0, m.viewport.Height())
	case offset >= 1:
		offset = clamp(offset+n, 1, m.viewport.Height())
	}
	m.viewport.SetYOffset(offset)
	m.UpdateViewport()
}

// MoveDown moves the selection down by n number of rows.
// It can not go below the last row.
func (m *Model) MoveDown(n int) {
	m.cursor[0] = clamp(m.cursor[0]+n, 0, len(m.rows)-1)

	offset := m.viewport.YOffset()
	switch {
	case m.end == len(m.rows) && offset > 0:
		offset = clamp(offset-n, 1, m.viewport.Height())
	case m.cursor[0] > (m.end-m.start)/2 && offset > 0:
		offset = clamp(offset-n, 1, m.cursor[0])
	case offset > 1:
	case m.cursor[0] > offset+m.viewport.Height()-1:
		offset = clamp(offset+1, 0, 1)
	}
	m.viewport.SetYOffset(offset)
	m.UpdateViewport()
}

// MoveLeft sets the table to cell selection mode and moves the selection left
// by n number of columns. It can not go past the first column.
func (m *Model) MoveLeft(n int) {
	m.mode = ModeCell
	m.cursor[1] = clamp(m.cursor[1]-n, 0, len(m.cols)-1)
	m.UpdateViewport()
}

// MoveRight sets the table to cell selection mode and moves the selection right
// by n number of columns. It can not go past the last column.
func (m *Model) MoveRight(n int) {
	m.mode = ModeCell
	m.cursor[1] = clamp(m.cursor[1]+n, 0, len(m.cols)-1)
	m.UpdateViewport()
}

// GotoTop moves the selection to the first row.
func (m *Model) GotoTop() {
	m.MoveUp(m.cursor[0])
}

// GotoBottom moves the selection to the last row.
func (m *Model) GotoBottom() {
	m.MoveDown(len(m.rows))
}

// SetMode sets the table mode.
func (m *Model) SetMode(md Mode) {
	m.mode = md
	if md == ModeNormal {
		m.cursor[1] = 0 // reset col
	}
	m.UpdateViewport()
}

// Mode returns the current table mode.
func (m Model) Mode() Mode {
	return m.mode
}

// FromValues create the table rows from a simple string. It uses `\n` by
// default for getting all the rows and the given separator for the fields on
// each row.
func (m *Model) FromValues(value, separator string) {
	rows := []Row{} //nolint:prealloc
	for _, line := range strings.Split(value, "\n") {
		r := Row{}
		for _, field := range strings.Split(line, separator) {
			r = append(r, field)
		}
		rows = append(rows, r)
	}

	m.SetRows(rows)
}

func (m Model) headersView() string {
	s := make([]string, 0, len(m.cols))
	for _, col := range m.cols {
		if col.Width <= 0 {
			continue
		}
		style := lipgloss.NewStyle().Width(col.Width).MaxWidth(col.Width).Inline(true)
		renderedCell := style.Render(ansi.Truncate(col.Title, col.Width, "…"))
		s = append(s, m.styles.Header.Render(renderedCell))
	}
	return lipgloss.JoinHorizontal(lipgloss.Top, s...)
}

func (m *Model) renderRow(r int) string {
	ctx := m.newRenderContext()
	s := make([]string, 0, len(m.cols))
	for c, value := range m.rows[r] {
		if m.cols[c].Width <= 0 {
			continue
		}

		ctx.Cell = [2]int{r, c}
		ctx.Value = value

		cellStyle := m.styles.Cell
		if m.styleFunc != nil {
			cellStyle = m.styleFunc(ctx)
		}

		if r == m.cursor[0] && c == m.cursor[1] && m.mode == ModeCell {
			cellStyle = cellStyle.Inherit(m.styles.Selected)
		}

		style := lipgloss.NewStyle().Width(m.cols[c].Width).MaxWidth(m.cols[c].Width).Inline(true)
		renderedCell := cellStyle.Render(style.Render(ansi.Truncate(value, m.cols[c].Width, "…")))
		s = append(s, renderedCell)
	}

	row := lipgloss.JoinHorizontal(lipgloss.Top, s...)

	if r == m.cursor[0] && m.mode == ModeNormal {
		return m.styles.Selected.Render(row)
	}

	return row
}

func (m *Model) newRenderContext() RenderContext {
	return RenderContext{
		Cursor:    m.cursor,
		Mode:      m.mode,
		IsFocused: m.focus,
	}
}

func clamp(v, low, high int) int {
	return min(max(v, low), high)
}
